services:
  - type: worker
    name: eureka-ip-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: TU_TOKEN_DEL_BOT
      - key: CONTENT_API_KEY
        value: TU_API_KEY_CONTENT
      - key: CONTENT_API_URL
        value: https://API_URL_EJEMPLO
      - key: IPDATA_API_KEY
        value: TU_API_KEY_IPDATA
      - key: IPINFO_ACCESS_TOKEN
        value: TU_API_KEY_IPINFO
      - key: SCRAPER_API_KEY
        value: TU_API_KEY_SCRAPER